# Generated by Django 4.1.6 on 2023-05-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booked_at_time", models.DateTimeField()),
                ("lead_passenger_contact_email", models.CharField(max_length=50)),
                ("lead_passenger_contact_number", models.CharField(max_length=50)),
                ("total_booking_cost", models.FloatField()),
                ("payment_confirmed", models.BooleanField(default=False)),
                ("transaction_id", models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=100)),
                ("continent", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="FlightInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_ticket_cost", models.FloatField()),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("departure_day", models.DateField()),
                ("num_available_seats", models.IntegerField()),
                (
                    "arrival_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_requests_created",
                        to="airline.country",
                    ),
                ),
                (
                    "departure_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="airline.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_capacity", models.IntegerField()),
                ("max_flight_distance", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SeatInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_name", models.CharField(max_length=50)),
                ("available", models.BooleanField()),
                (
                    "flight_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="airline.flightinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("passport_number", models.CharField(max_length=50)),
                (
                    "booking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airline.bookinginstance",
                    ),
                ),
                (
                    "nationality_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="airline.country",
                    ),
                ),
                (
                    "seat_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="airline.seatinstance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flightinstance",
            name="plane_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="airline.plane"
            ),
        ),
    ]
