# Generated by Django 4.2 on 2023-05-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=50)),
                ("continent", models.CharField(max_length=50)),
                ("longitude", models.IntegerField()),
                ("latitude", models.IntegerField()),
            ],
        ),
    ]
