# Generated by Django 4.2 on 2023-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country", name="latitude", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="country", name="longitude", field=models.FloatField(),
        ),
    ]
