# Generated by Django 4.2 on 2023-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0002_alter_country_latitude_alter_country_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_ID", models.IntegerField()),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("nationality_country_ID", models.IntegerField()),
                ("passport_num", models.CharField(max_length=50)),
                ("seat_ID", models.IntegerField()),
            ],
        ),
    ]
