# Generated by Django 4.1.6 on 2023-05-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0002_bookinginstance_pending"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookinginstance", name="pending",),
    ]
