# Generated by Django 4.2 on 2023-05-03 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0003_passenger"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booked_at_time", models.DateField()),
                ("lead_passenger_contact_email", models.CharField(max_length=50)),
                ("lead_passenger_contact_number", models.CharField(max_length=50)),
                ("total_booking_cost", models.FloatField()),
                ("payment_confirmed", models.BooleanField()),
                ("transaction_ID", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="passenger",
            name="nationality_country_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="airline.country"
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="booking_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="airline.bookinginstance",
            ),
        ),
    ]
