# Generated by Django 4.2 on 2023-05-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0004_bookinginstance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_capacity", models.IntegerField()),
                ("max_flight_distance", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="passenger",
            name="booking_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="airline.bookinginstance",
            ),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="nationality_country_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="airline.country"
            ),
        ),
        migrations.CreateModel(
            name="FlightInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_ticket_cost", models.FloatField()),
                ("departure_time", models.DateField()),
                ("arrival_time", models.DateField()),
                ("num_available_seats", models.IntegerField()),
                (
                    "arrival_location_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_requests_created",
                        to="airline.country",
                    ),
                ),
                (
                    "departure_location_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="airline.country",
                    ),
                ),
                (
                    "plane_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="airline.plane"
                    ),
                ),
            ],
        ),
    ]
