# Generated by Django 4.2 on 2023-05-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0005_plane_alter_passenger_booking_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_name", models.CharField(max_length=50)),
                ("available", models.BooleanField()),
                (
                    "flight_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="airline.flightinstance",
                    ),
                ),
            ],
        ),
    ]
