# Generated by Django 4.2 on 2023-05-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0006_seatinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="seat_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="airline.seatinstance"
            ),
        ),
    ]
