# Generated by Django 4.2 on 2023-05-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0007_alter_passenger_seat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinginstance",
            name="booked_at_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="flightinstance",
            name="arrival_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="flightinstance",
            name="departure_time",
            field=models.DateTimeField(),
        ),
    ]
