# Generated by Django 4.2 on 2023-05-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0008_alter_bookinginstance_booked_at_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightinstance",
            name="arrival_day",
            field=models.DateField(default="2023-05-03"),
            preserve_default=False,
        ),
    ]
