# Generated by Django 4.2 on 2023-05-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0009_flightinstance_arrival_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinginstance",
            name="payment_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bookinginstance",
            name="transaction_ID",
            field=models.IntegerField(blank=True),
        ),
    ]
